package com.music.project.entities;
// Generated Jan 4, 2025, 3:25:22 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * AlbumUserId generated by hbm2java
 */
@Embeddable
public class AlbumUserId implements java.io.Serializable {

	private Integer userId;
	private Integer albumId;
	private Date createdAt;
	private Date updateAt;

	public AlbumUserId() {
	}

	public AlbumUserId(Integer userId, Integer albumId, Date createdAt, Date updateAt) {
		this.userId = userId;
		this.albumId = albumId;
		this.createdAt = createdAt;
		this.updateAt = updateAt;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "album_id")
	public Integer getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	@Column(name = "created_at", length = 26)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "update_at", length = 26)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlbumUserId))
			return false;
		AlbumUserId castOther = (AlbumUserId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getAlbumId() == castOther.getAlbumId()) || (this.getAlbumId() != null
						&& castOther.getAlbumId() != null && this.getAlbumId().equals(castOther.getAlbumId())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getUpdateAt() == castOther.getUpdateAt()) || (this.getUpdateAt() != null
						&& castOther.getUpdateAt() != null && this.getUpdateAt().equals(castOther.getUpdateAt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getAlbumId() == null ? 0 : this.getAlbumId().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getUpdateAt() == null ? 0 : this.getUpdateAt().hashCode());
		return result;
	}

}
