package com.music.project.entities;
// Generated Jan 4, 2025, 3:25:22 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", uniqueConstraints = @UniqueConstraint(columnNames = "slug"))
public class Album implements java.io.Serializable {

	private Integer id;
	private String name;
	private String slug;
	private String photo;
	private Date releaseDay;
	private Date createdAt;
	private Date updateAt;
	private Set<AlbumUser> albumUsers = new HashSet<AlbumUser>(0);
	private Set<Song> songs = new HashSet<Song>(0);

	public Album() {
	}

	public Album(String name) {
		this.name = name;
	}

	public Album(String name, String slug, String photo, Date releaseDay, Date createdAt, Date updateAt,
			Set<AlbumUser> albumUsers, Set<Song> songs) {
		this.name = name;
		this.slug = slug;
		this.photo = photo;
		this.releaseDay = releaseDay;
		this.createdAt = createdAt;
		this.updateAt = updateAt;
		this.albumUsers = albumUsers;
		this.songs = songs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slug", unique = true)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "photo", length = 400)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_day", length = 26)
	public Date getReleaseDay() {
		return this.releaseDay;
	}

	public void setReleaseDay(Date releaseDay) {
		this.releaseDay = releaseDay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 26)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 26)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<AlbumUser> getAlbumUsers() {
		return this.albumUsers;
	}

	public void setAlbumUsers(Set<AlbumUser> albumUsers) {
		this.albumUsers = albumUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<Song> getSongs() {
		return this.songs;
	}

	public void setSongs(Set<Song> songs) {
		this.songs = songs;
	}

}
