package com.music.project.entities;
// Generated Jan 4, 2025, 3:25:22 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre", uniqueConstraints = @UniqueConstraint(columnNames = "slug"))
public class Genre implements java.io.Serializable {

	private Integer id;
	private String name;
	private String slug;
	private String photo;
	private Date createdAt;
	private Date updateAt;
	private Set<SongGenre> songGenres = new HashSet<SongGenre>(0);

	public Genre() {
	}

	public Genre(String name) {
		this.name = name;
	}

	public Genre(String name, String slug, String photo, Date createdAt, Date updateAt, Set<SongGenre> songGenres) {
		this.name = name;
		this.slug = slug;
		this.photo = photo;
		this.createdAt = createdAt;
		this.updateAt = updateAt;
		this.songGenres = songGenres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slug", unique = true)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "photo", length = 400)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 26)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 26)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<SongGenre> getSongGenres() {
		return this.songGenres;
	}

	public void setSongGenres(Set<SongGenre> songGenres) {
		this.songGenres = songGenres;
	}

}
