package com.music.project.entities;
// Generated Jan 4, 2025, 3:25:22 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Playlist generated by hbm2java
 */
@Entity
@Table(name = "playlist", uniqueConstraints = @UniqueConstraint(columnNames = "slug"))
public class Playlist implements java.io.Serializable {

	private Integer id;
	private User user;
	private String name;
	private String slug;
	private String photo;
	private Date createdAt;
	private Date updateAt;
	private Set<PlaylistSong> playlistSongs = new HashSet<PlaylistSong>(0);

	public Playlist() {
	}

	public Playlist(User user, String name) {
		this.user = user;
		this.name = name;
	}

	public Playlist(User user, String name, String slug, String photo, Date createdAt, Date updateAt,
			Set<PlaylistSong> playlistSongs) {
		this.user = user;
		this.name = name;
		this.slug = slug;
		this.photo = photo;
		this.createdAt = createdAt;
		this.updateAt = updateAt;
		this.playlistSongs = playlistSongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slug", unique = true)
	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	@Column(name = "photo", length = 400)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 26)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 26)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "playlist")
	public Set<PlaylistSong> getPlaylistSongs() {
		return this.playlistSongs;
	}

	public void setPlaylistSongs(Set<PlaylistSong> playlistSongs) {
		this.playlistSongs = playlistSongs;
	}

}
