package com.music.project.entities;
// Generated Jan 4, 2025, 3:25:22 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PlaylistSong generated by hbm2java
 */
@Entity
@Table(name = "playlist_song")
public class PlaylistSong implements java.io.Serializable {

	private PlaylistSongId id;
	private Playlist playlist;
	private Song song;

	public PlaylistSong() {
	}

	public PlaylistSong(PlaylistSongId id) {
		this.id = id;
	}

	public PlaylistSong(PlaylistSongId id, Playlist playlist, Song song) {
		this.id = id;
		this.playlist = playlist;
		this.song = song;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "playlistId", column = @Column(name = "playlist_id")),
			@AttributeOverride(name = "songId", column = @Column(name = "song_id")),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 26)),
			@AttributeOverride(name = "updateAt", column = @Column(name = "update_at", length = 26)) })
	public PlaylistSongId getId() {
		return this.id;
	}

	public void setId(PlaylistSongId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "playlist_id", insertable = false, updatable = false)
	public Playlist getPlaylist() {
		return this.playlist;
	}

	public void setPlaylist(Playlist playlist) {
		this.playlist = playlist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_id", insertable = false, updatable = false)
	public Song getSong() {
		return this.song;
	}

	public void setSong(Song song) {
		this.song = song;
	}

}
