package com.music.project.entities;
// Generated Jan 4, 2025, 3:25:22 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Builder;

/**
 * SongArtist generated by hbm2java
 */
@Entity
@Table(name = "song_artist")
@Builder
public class SongArtist implements java.io.Serializable {

	private SongArtistId id;
	private Song song;
	private User user;

	public SongArtist() {
	}

	public SongArtist(SongArtistId id) {
		this.id = id;
	}

	public SongArtist(SongArtistId id, Song song, User user) {
		this.id = id;
		this.song = song;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id")),
			@AttributeOverride(name = "songId", column = @Column(name = "song_id")),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 26)),
			@AttributeOverride(name = "updateAt", column = @Column(name = "update_at", length = 26)) })
	public SongArtistId getId() {
		return this.id;
	}

	public void setId(SongArtistId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_id", insertable = false, updatable = false)
	public Song getSong() {
		return this.song;
	}

	public void setSong(Song song) {
		this.song = song;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
