package com.music.project.entities;
// Generated Jan 4, 2025, 3:25:22 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * SongGenre generated by hbm2java
 */
@Entity
@Table(name = "song_genre")
public class SongGenre implements java.io.Serializable {

	private SongGenreId id;
	private Genre genre;
	private Song song;

	public SongGenre() {
	}

	public SongGenre(SongGenreId id) {
		this.id = id;
	}

	public SongGenre(SongGenreId id, Genre genre, Song song) {
		this.id = id;
		this.genre = genre;
		this.song = song;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "songId", column = @Column(name = "song_id")),
			@AttributeOverride(name = "genreId", column = @Column(name = "genre_id")),
			@AttributeOverride(name = "createdAt", column = @Column(name = "created_at", length = 26)),
			@AttributeOverride(name = "updateAt", column = @Column(name = "update_at", length = 26)) })
	public SongGenreId getId() {
		return this.id;
	}

	public void setId(SongGenreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genre_id", insertable = false, updatable = false)
	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "song_id", insertable = false, updatable = false)
	public Song getSong() {
		return this.song;
	}

	public void setSong(Song song) {
		this.song = song;
	}

}
