package com.music.project.entities;
// Generated Jan 4, 2025, 3:25:22 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SongGenreId generated by hbm2java
 */
@Embeddable
public class SongGenreId implements java.io.Serializable {

	private Integer songId;
	private Integer genreId;
	private Date createdAt;
	private Date updateAt;

	public SongGenreId() {
	}

	public SongGenreId(Integer songId, Integer genreId, Date createdAt, Date updateAt) {
		this.songId = songId;
		this.genreId = genreId;
		this.createdAt = createdAt;
		this.updateAt = updateAt;
	}

	@Column(name = "song_id")
	public Integer getSongId() {
		return this.songId;
	}

	public void setSongId(Integer songId) {
		this.songId = songId;
	}

	@Column(name = "genre_id")
	public Integer getGenreId() {
		return this.genreId;
	}

	public void setGenreId(Integer genreId) {
		this.genreId = genreId;
	}

	@Column(name = "created_at", length = 26)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "update_at", length = 26)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SongGenreId))
			return false;
		SongGenreId castOther = (SongGenreId) other;

		return ((this.getSongId() == castOther.getSongId()) || (this.getSongId() != null
				&& castOther.getSongId() != null && this.getSongId().equals(castOther.getSongId())))
				&& ((this.getGenreId() == castOther.getGenreId()) || (this.getGenreId() != null
						&& castOther.getGenreId() != null && this.getGenreId().equals(castOther.getGenreId())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getUpdateAt() == castOther.getUpdateAt()) || (this.getUpdateAt() != null
						&& castOther.getUpdateAt() != null && this.getUpdateAt().equals(castOther.getUpdateAt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSongId() == null ? 0 : this.getSongId().hashCode());
		result = 37 * result + (getGenreId() == null ? 0 : this.getGenreId().hashCode());
		result = 37 * result + (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result + (getUpdateAt() == null ? 0 : this.getUpdateAt().hashCode());
		return result;
	}

}
